name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          IMAGE=$(aws ecr describe-repositories --repository-names ror-app-repo --query 'repositories[0].repositoryUri' --output text)
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init

      - name: Import existing resources (if needed)
        working-directory: infrastructure
        run: |
          terraform import aws_ecr_repository.app ror-app-repo || true
          terraform import aws_iam_role.ecs_exec ecs-exec-role || true
          terraform import aws_lb.app ror-lb || true
          terraform import aws_lb_target_group.app ror-tg || true
          terraform import aws_db_subnet_group.default ror-db-subnet-group || true

      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve
